from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path

from erpqa.core.constants import SOURCE_CATEGORIES
from erpqa.core.paths import ensure_qa_context, write_text, write_yaml


def _module_for(path: Path) -> str:
    lowered = path.as_posix().lower()
    for module in ("inventory", "purchase", "production", "shipment"):
        if module in lowered:
            return module
    return "general"


def _classify(path: Path) -> tuple[str, str, bool]:
    parts = {part.lower() for part in path.parts}
    name = path.name.lower()
    suffix = path.suffix.lower()
    if "db_schema" in parts or "schema" in name or suffix == ".sql":
        return "db_schema", "high", False
    if "api_specs" in parts or "openapi" in name or "swagger" in name:
        return "api_specs", "high", False
    if "screen_specs" in parts or "screen" in name or "wireframe" in name:
        return "screen_specs", "high", False
    if "backend" in parts or suffix in {".py", ".rb", ".java", ".kt", ".go", ".cs"}:
        return "backend", "medium", True
    if "frontend" in parts or suffix in {".js", ".jsx", ".ts", ".tsx", ".vue", ".svelte", ".html", ".css"}:
        return "frontend", "medium", True
    if "docs" in parts or suffix in {".md", ".txt", ".rst"}:
        return "docs", "high", False
    return "docs", "low", True


def discover_sources(project_path: str | Path) -> list[dict[str, object]]:
    root = Path(project_path).resolve()
    rows: list[dict[str, object]] = []
    for file in sorted(root.rglob("*")):
        if not file.is_file():
            continue
        rel = file.relative_to(root)
        if rel.parts and rel.parts[0] in {"qa-context", ".git", ".pytest_cache", "__pycache__"}:
            continue
        category, confidence, needs = _classify(rel)
        rows.append(
            {
                "path": rel.as_posix(),
                "category": category,
                "module": _module_for(rel),
                "source": f"intake heuristic from {rel.as_posix()}",
                "confidence": confidence,
                "needs_human_confirmation": needs,
            }
        )
    return rows


def render_source_inventory(rows: list[dict[str, object]]) -> str:
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[str(row["category"])].append(row)

    lines = [
        "# Source Inventory",
        "",
        "Generated by `erpqa intake`. Classification is heuristic and reviewable.",
        "",
    ]
    for category in SOURCE_CATEGORIES:
        lines.extend([f"## {category}", ""])
        if not grouped.get(category):
            lines.append("_No files detected._")
        for row in grouped.get(category, []):
            lines.append(
                "- `{path}` | module: `{module}` | confidence: `{confidence}` | "
                "needs_human_confirmation: `{needs_human_confirmation}` | source: {source}".format(**row)
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def run_intake(project_path: str | Path) -> tuple[int, Path, Path]:
    ensure_qa_context(project_path)
    rows = discover_sources(project_path)
    if not rows:
        raise ValueError("no source files found outside qa-context")

    inventory_path = write_text(project_path, "source_inventory.md", render_source_inventory(rows))
    modules = sorted({str(row["module"]) for row in rows})
    counts = Counter(str(row["category"]) for row in rows)
    manifest = {
        "project": {
            "name": Path(project_path).resolve().name,
            "target_root": ".",
            "source": "erpqa intake project folder scan",
            "confidence": "medium",
            "needs_human_confirmation": True,
        },
        "modules": modules,
        "source_inventory": rows,
        "category_counts": {category: counts.get(category, 0) for category in SOURCE_CATEGORIES},
    }
    manifest_path = write_yaml(project_path, "project_manifest.yaml", manifest)
    return len(rows), inventory_path, manifest_path

